[package]
name = "td-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hecs = "0.7.1"
rand = "0.8.4"
log = "0.4.0"
env_logger = "0.8.4"
clap = "2.34.0"
anyhow = "1.0.51"
macroquad = "0.3"